name: gradeslide
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flushbar: ^1.10.4
  get:
  flutter:
    sdk: flutter

  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.4.2
  provider:
  firebase_core: ^0.4.3+1
  cloud_firestore: any
  firebase_auth:
  flare_flutter: any
  share: ^0.6.2+3
  flutter_speed_dial: ^1.2.1
  fl_chart: ^0.9.2
  flutter_slidable: ^0.5.5
  flutter_twitter: ^1.1.3
  lit_firebase_auth: ^0.2.3
  material_design_icons_flutter: 4.0.5655
  draggable_scrollbar: ^0.0.4
  pull_to_refresh: ^1.6.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/icon.png"

flutter:
  fonts:
    - family: Fredoka
      fonts:
        - asset: fonts/FredokaOne.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
    - family: Montserrat-Thin
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: Montserrat-ExtraBold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Fira
      fonts:
        - asset: fonts/FiraSansCondensed-Bold.ttf
    - family: Teko
      fonts:
        - asset: fonts/Teko-Bold.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf


  assets:
      - images/vision.png
      - images/pencil.png
      - images/outlinedpencil.png
      - images/mainlogo.png
      - flares/progbar.flr
      - assets/progbar.flr

  uses-material-design: true
